# fly.toml
# This is the main configuration file for Fly.io.
# It tells Fly how to build, deploy, and run your application.

app = 'pharmacy-stock-system' # Choose a unique name for your app
primary_region = 'sin' # Example: Singapore. Choose a region close to you.

[build]
  builder = "paketobuildpacks/builder-jammy-base"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

# This section defines a persistent volume for our database.
# This is CRITICAL because the app's main filesystem is temporary.
[mounts]
  source="pharmacy_data"
  destination="/data"
