# .github/workflows/fly-deploy.yml
# This file defines the automatic deployment process.

name: Fly Deploy

on:
  # This action runs automatically whenever you push code to the 'main' branch.
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code from your repository so the action can use it.
      - uses: actions/checkout@v3

      # Step 2: Set up the Fly.io command-line tool, flyctl.
      - uses: superfly/flyctl-actions/setup-flyctl@master

      # Step 3: Deploy the app to Fly.io.
      # It uses the FLY_API_TOKEN you stored in GitHub Secrets to authenticate.
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
